<?php

/**
 * Implements hook_theme_suggestions_HOOK_alter() for views templates.
 */
function acquia_dam_integration_theme_suggestions_views_view_field_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  $display_id = $view->current_display;
  $field_name = $variables['field']->field;

  if ($view->id() == 'product_variants' && $display_id == 'block_1' && $field_name == 'field_attr_color') {
    $suggestions[] = 'views_view_field__product_variants__block_1__field_attr_color';
  }
  elseif ($view->id() == 'products' && $display_id == 'page_1' && $field_name == 'field_attr_color') {
    $suggestions[] = 'views_view_field__product_variants__block_1__field_attr_color';
  }
}

/**
 * Implements hook_theme().
 */
function acquia_dam_integration_theme($existing, $type, $theme, $path) {
  return [
    'views_view_field__product_variants__block_1__field_attr_color' => [
      'template' => 'views-view-field--product-variants--block-1--field-attr-color',
      'base hook' => 'views',
    ],
  ];
}

